/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ResearchRole;

import Business.EcoSystem;
import Business.Enterprise.Comunity.CommunityEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HealthcareCenter.HealthCareCenterEnterprise;
import Business.Network.Network;
import Business.Organization.Community.FamilyOrganization;
import Business.Organization.HealthCare.ResearchOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FamilyHealthWorkRequest;
import Business.WorkQueue.HealthFamilyWorkRequest;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.StoreHealthWorkRequest;
import Business.WorkQueue.WorkRequest;
import Refrigerator.ConsumedProudcts;
import Refrigerator.HomeRefrigerator;
import Refrigerator.Product;
import Refrigerator.ProductDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class ResearchWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Organization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
     private EcoSystem business;
     String id;
    private  ConsumedProudcts consumedProudcts;
 
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public ResearchWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization,
            Enterprise enterprise, EcoSystem business ) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
        valueLabel.setText(enterprise.getName());
       
        populateRequestTable();
         
    }
    
    public void populateRequestTable(){
      DefaultTableModel model = (DefaultTableModel) WorkRequestJTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
            
            Object[] row = new Object[4];
            row[0] = request;
            row[1] = request.getStatus();
            row[2] = request.getResult();
            
            
            model.addRow(row);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestTestJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        WorkRequestJTable = new javax.swing.JTable();
        sendFamilyStatusJBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        requestTestJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        requestTestJButton.setText("Request Test");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton);
        requestTestJButton.setBounds(180, 250, 170, 25);

        enterpriseLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel);
        enterpriseLabel.setBounds(30, 80, 160, 30);

        valueLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel);
        valueLabel.setBounds(170, 80, 190, 26);

        WorkRequestJTable.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        WorkRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Status", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(WorkRequestJTable);
        if (WorkRequestJTable.getColumnModel().getColumnCount() > 0) {
            WorkRequestJTable.getColumnModel().getColumn(0).setResizable(false);
            WorkRequestJTable.getColumnModel().getColumn(1).setResizable(false);
            WorkRequestJTable.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane2);
        jScrollPane2.setBounds(20, 120, 550, 90);

        sendFamilyStatusJBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sendFamilyStatusJBtn.setText("Send Family Status");
        sendFamilyStatusJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendFamilyStatusJBtnActionPerformed(evt);
            }
        });
        add(sendFamilyStatusJBtn);
        sendFamilyStatusJBtn.setBounds(180, 280, 170, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/ResearchRole/lab and research.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, -20, 600, 530);
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed
   
int selectedRow=WorkRequestJTable.getSelectedRow();
        int  row=WorkRequestJTable.getSelectedRow();
        if (row < 0) {
           JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
           return;
       }
      WorkRequest request=(WorkRequest)WorkRequestJTable.getValueAt(selectedRow, 0);
      id=request.getFamilyID();
       consumedProudcts=request.getProductDirectory();
    
       CardLayout layout = (CardLayout) userProcessContainer.getLayout();
       userProcessContainer.add("RequestLabTestJPanel", new RequestLabTestJPanel(userProcessContainer,id,consumedProudcts,userAccount,organization, enterprise));
       layout.next(userProcessContainer);
        //organization.getWorkQueue().removeWorkRequest(request);
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void sendFamilyStatusJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendFamilyStatusJBtnActionPerformed
        // TODO add your handling code here:


int  row=WorkRequestJTable.getSelectedRow();
        if (row < 0) {
           JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
           return;
       }
       
          WorkRequest request = (WorkRequest)WorkRequestJTable.getValueAt(row, 0); 
    
        HealthFamilyWorkRequest req = new HealthFamilyWorkRequest();

       req.setSender(userAccount);
       req.setStatus("Complete");
       req.setFamilyID(request.getFamilyID());
       req.setResultsDir(request.getResultsDir());
       
       
     
       Enterprise enter=null;
       Organization org = null;
       UserAccount uasre=null;

       for (Network net : business.getNetworkList()) {
           for (Enterprise enterprise : net.getEnterpriseDirectory().getEnterpriseList()) {
               if (enterprise instanceof CommunityEnterprise) {
                   enter=enterprise;
                   for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                       if (organization instanceof FamilyOrganization) {
                           org = organization;
                        for( UserAccount ua:  organization.getUserAccountDirectory().getUserAccountList()){
                            if(ua.getUsername().equals(request.getFamilyID()))
                                
                                uasre=ua;
                             break;
                        } 
                          
                       }
                   }
               }

           }
       }
       if (uasre != null) {
          // org.getWorkQueue().getWorkRequestList().add(req);
          // enter.getWorkQueue().getWorkRequestList().add(req);
         uasre.getWorkQueue().getWorkRequestList().add(req);
           
       }

        
  JOptionPane.showMessageDialog(null, "result sent! ", "Information", JOptionPane.INFORMATION_MESSAGE);
  //organization.getWorkQueue().removeWorkRequest(request);
  populateRequestTable();        
    }//GEN-LAST:event_sendFamilyStatusJBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable WorkRequestJTable;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JButton sendFamilyStatusJBtn;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
