/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FamilyRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Community.FamilyOrganization;
import Business.UserAccount.UserAccount;
import Refrigerator.Product;
import Refrigerator.ProductDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author lenovo
 */
public class SetFamilyRefPeoudcts extends javax.swing.JPanel {

 private JPanel userProcessContainer;
private FamilyOrganization organization;
private Enterprise enterprise;
private UserAccount userAccount;
 private EcoSystem business;
 private static  int milikConsumed=0;
    /**
     * Creates new form FamilyRefrigeratorWorkQueue
     */
    public SetFamilyRefPeoudcts(JPanel userProcessContainer, Enterprise enterprise, FamilyOrganization organization, UserAccount account,EcoSystem business) {
        initComponents();
        this.organization= organization;
        this.userProcessContainer= userProcessContainer;
        this.enterprise=enterprise;
        this.userAccount= account;
        this.business=business;
        
      
    }
    
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFProudctNmae = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtProudctAvailabilty = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtProudctExpirationDate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel1.setText("Proudct Name:");
        add(jLabel1);
        jLabel1.setBounds(370, 160, 92, 20);

        txtFProudctNmae.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        txtFProudctNmae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFProudctNmaeActionPerformed(evt);
            }
        });
        add(txtFProudctNmae);
        txtFProudctNmae.setBounds(370, 190, 70, 20);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel2.setText("Proudct Availabilty");
        add(jLabel2);
        jLabel2.setBounds(370, 220, 92, 20);

        txtProudctAvailabilty.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        txtProudctAvailabilty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProudctAvailabiltyActionPerformed(evt);
            }
        });
        add(txtProudctAvailabilty);
        txtProudctAvailabilty.setBounds(370, 250, 70, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 8)); // NOI18N
        jLabel3.setText("Proudct Expiration Date");
        jLabel3.setEnabled(false);
        add(jLabel3);
        jLabel3.setBounds(370, 280, 110, 20);

        txtProudctExpirationDate.setEnabled(false);
        txtProudctExpirationDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProudctExpirationDateActionPerformed(evt);
            }
        });
        add(txtProudctExpirationDate);
        txtProudctExpirationDate.setBounds(370, 310, 70, 20);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jButton1.setText("SET Product");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(370, 350, 90, 23);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/FamilyRole/back-icon.png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(0, 481, 100, 20);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/FamilyRole/ref2.jpg"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(50, 10, 510, 490);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFProudctNmaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFProudctNmaeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFProudctNmaeActionPerformed

    private void txtProudctAvailabiltyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProudctAvailabiltyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProudctAvailabiltyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

  try{
     
      
       String pN = txtFProudctNmae.getText();
         int avaliNum= Integer.parseInt(txtProudctAvailabilty.getText());
              if(avaliNum>0 && pN.length()>0 )
              {
                   Product p=organization.getHomeRefrigerator().getProductDirectory().addProduct();
                p.setName(pN);
             p.setStock(avaliNum);
                
             
       txtFProudctNmae.setText("");
       txtProudctAvailabilty.setText("");
       
         JOptionPane.showMessageDialog(null, "Products Added successfully ", "Informaton", JOptionPane.INFORMATION_MESSAGE);
              }
     else
              {throw new Exception();}
            
              
        
}

catch(Exception e){

  JOptionPane.showMessageDialog(null,"Please re-enter fields","ERROR",JOptionPane.ERROR_MESSAGE);
  txtFProudctNmae.setText("");
  txtProudctAvailabilty.setText("");
}
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtProudctExpirationDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProudctExpirationDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProudctExpirationDateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtFProudctNmae;
    private javax.swing.JTextField txtProudctAvailabilty;
    private javax.swing.JTextField txtProudctExpirationDate;
    // End of variables declaration//GEN-END:variables
}
