/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StroreRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Community.StoreOrganization;
import Business.UserAccount.UserAccount;
import Refrigerator.Product;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author lenovo
 */
public class SetStoreProudctJPanel extends javax.swing.JPanel {

    private Enterprise enterprise;
    private StoreOrganization organization;
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private EcoSystem business;

    /**
     * Creates new form SetStoreProudctJPanel
     */
    public SetStoreProudctJPanel(JPanel userProcessContainer, Enterprise enterprise,
            StoreOrganization organization, UserAccount account, EcoSystem business) {
        initComponents();
        this.organization = organization;
        this.enterprise = enterprise;
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
    }

    public void initProducts() {

        Product p = organization.getStoreRefrigerator().getProductDirectory().addProduct();

        p.setName(txtFProudctNmae.getText());
        p.setStock(Integer.parseInt(txtProudctAvailabilty.getText()));
        p.setExpirationDate(txtProductPrice.getText());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtFProudctNmae = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtProudctAvailabilty = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtProductPrice = new javax.swing.JTextField();
        setProduct = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setLayout(null);

        jLabel1.setText("Product Name:");
        add(jLabel1);
        jLabel1.setBounds(390, 170, 92, 20);

        txtFProudctNmae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFProudctNmaeActionPerformed(evt);
            }
        });
        add(txtFProudctNmae);
        txtFProudctNmae.setBounds(390, 190, 80, 20);

        jLabel2.setText("Proudct Availabilty");
        add(jLabel2);
        jLabel2.setBounds(390, 220, 92, 20);

        txtProudctAvailabilty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProudctAvailabiltyActionPerformed(evt);
            }
        });
        add(txtProudctAvailabilty);
        txtProudctAvailabilty.setBounds(390, 240, 90, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 8)); // NOI18N
        jLabel3.setText("Price");
        add(jLabel3);
        jLabel3.setBounds(390, 280, 120, 20);

        txtProductPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductPriceActionPerformed(evt);
            }
        });
        add(txtProductPrice);
        txtProductPrice.setBounds(390, 300, 90, 20);

        setProduct.setText("Set Proudct");
        setProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setProductActionPerformed(evt);
            }
        });
        add(setProduct);
        setProduct.setBounds(390, 340, 90, 23);

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/StroreRole/back-icon.png"))); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton);
        backButton.setBounds(0, 460, 91, 41);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/StroreRole/roban.png"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(-40, 0, 510, 90);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/StroreRole/ref2.jpg"))); // NOI18N
        add(jLabel6);
        jLabel6.setBounds(70, 30, 630, 480);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFProudctNmaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFProudctNmaeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFProudctNmaeActionPerformed

    private void txtProudctAvailabiltyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProudctAvailabiltyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProudctAvailabiltyActionPerformed

    private void txtProductPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductPriceActionPerformed

    private void setProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setProductActionPerformed
        // TODO add your handling code here:

        try {

            String pN = txtFProudctNmae.getText();
            int avaliNum = Integer.parseInt(txtProudctAvailabilty.getText());
            if (avaliNum > 0 && pN.length() > 0) {
                Product p = organization.getStoreRefrigerator().getProductDirectory().addProduct();
                p.setName(pN);
                p.setStock(avaliNum);
                p.setPrice(Integer.parseInt(txtProductPrice.getText()));

                txtFProudctNmae.setText("");
                txtProudctAvailabilty.setText("");
                txtProductPrice.setText("");

                JOptionPane.showMessageDialog(null, "Products Added successfully ", "Informaton", JOptionPane.INFORMATION_MESSAGE);
            } else {
                throw new Exception();
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Please re-enter fields", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtFProudctNmae.setText("");
            txtProudctAvailabilty.setText("");
        }
    }//GEN-LAST:event_setProductActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton setProduct;
    private javax.swing.JTextField txtFProudctNmae;
    private javax.swing.JTextField txtProductPrice;
    private javax.swing.JTextField txtProudctAvailabilty;
    // End of variables declaration//GEN-END:variables
}
