/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StroreRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Community.StoreOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author lenovo
 */
public class StoreRoleWorkArea extends javax.swing.JPanel {

    private Enterprise enterprise;
    private StoreOrganization organization;
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private EcoSystem business;

    /**
     * Creates new form StoreWorkQueue
     */
    public StoreRoleWorkArea(JPanel userProcessContainer, UserAccount account, StoreOrganization organization,
            Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.organization = organization;
        this.enterprise = enterprise;
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refrigeratoBtn = new javax.swing.JButton();
        refrigeratoBtn1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setLayout(null);

        refrigeratoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrigeratoBtnActionPerformed(evt);
            }
        });
        add(refrigeratoBtn);
        refrigeratoBtn.setBounds(210, 220, 10, 110);

        refrigeratoBtn1.setText("Set StoreProudcts");
        refrigeratoBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrigeratoBtn1ActionPerformed(evt);
            }
        });
        add(refrigeratoBtn1);
        refrigeratoBtn1.setBounds(290, 110, 119, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/StroreRole/ref.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        add(jLabel5);
        jLabel5.setBounds(0, 0, 590, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void refrigeratoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrigeratoBtnActionPerformed
        // TODO add your handling code here:
        StoreRefrigeratorJPanel panel = new StoreRefrigeratorJPanel(userProcessContainer, enterprise,
                organization, userAccount, business);

        userProcessContainer.add("StoreRefrigeratorJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_refrigeratoBtnActionPerformed

    private void refrigeratoBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrigeratoBtn1ActionPerformed
        // TODO add your handling code here:
        SetStoreProudctJPanel panel = new SetStoreProudctJPanel(userProcessContainer, enterprise,
                organization, userAccount, business);

        userProcessContainer.add("SetStoreProudctJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_refrigeratoBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton refrigeratoBtn;
    private javax.swing.JButton refrigeratoBtn1;
    // End of variables declaration//GEN-END:variables
}
